baseURL = 'https://mentalflow.pages.dev'
languageCode = 'en-us'
title = 'mentalflow'
theme = 'paperMod'
googleAnalytics = 'G-NCDHNEYW02'

[params.utteranc]
    enable = true
    repo = "liuzehao/mentalflowtalk"
    issueTerm = "pathname"
    theme = "github-light"